### ISSUE TITLE
solaredge_openapi restarting

### ISSUE THREAD

**Issue by Jonoas** [matjazbravc/SolarEdge.Monitoring.Demo#2]
In the log I found

2024-11-10 10:45:01 Unhandled exception. System.InvalidOperationException: The 'Configure' method in the type 'SolarEdge.Monitoring.Demo.Startup' must have a return type of 'Void'.
2024-11-10 10:45:01    at Microsoft.AspNetCore.Hosting.StartupLoader.FindMethod(Type startupType, String methodName, String environmentName, Type returnType, Boolean required)
2024-11-10 10:45:01    at Microsoft.AspNetCore.Hosting.StartupLoader.FindConfigureDelegate(Type startupType, String environmentName)
2024-11-10 10:45:01    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
2024-11-10 10:45:01    at Microsoft.Extensions.Hosting.HostBuilder.InitializeServiceProvider()
2024-11-10 10:45:01    at Microsoft.Extensions.Hosting.HostBuilder.Build()
2024-11-10 10:45:01    at Program.<Main>$(String[] args) in /src/src/SolarEdge.Monitoring.Demo/Program.cs:line 37
2024-11-10 10:45:01    at Program.<Main>(String[] args)

I only changed the two parameter in the override file. It look for me that the problem ist the async implementation of Configure. I have no expience in ASP.NET core. Can you help me?

**Comment by matjaz-bravc-ctg** [comment]
Thank you @Jonoas, I've fixed problem, please make a pull.

**Comment by Jonoas** [comment]
Thanks @matjazbravc for your fast response. Now it start and I have one row, for today in the mysql tables. Great! 

When I now click in the docker UI on the _localhost:port_, only localhost:3000 open a browser window with result. On localhost:3306 (ERR_INVALID_HTTP_RESPONSE) and localhost:9900 (ERR_CONNECTION_RESET). I very new in docker so I not sure if it necessary to change something im my operating system. I use mac os 15.1. 

I check the log files and found no error. I think I have aproblem to access the ports, firewall disabled. Have you idea?
